name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dist -- -p never
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist_apps/*.exe
            dist_apps/*.dmg
            dist_apps/*.AppImage
            dist_apps/*.deb
            dist_apps/*.zip
            dist_apps/*.blockmap
            dist_apps/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}